### ISSUE TITLE
Enhanced Session Mode not available.

### ISSUE THREAD

**Issue by liamfoneill** [Microsoft/linux-vm-tools#10]
I followed the guide on Technet however when I launch my Ubuntu 16.04 VM it doesn't prompt me for screen size and just boots. in the View menu of Hyper-V Enhanced Session is greyed out.

On the Ubuntu 16.04 I ran "systemctl list-units --type service" and I can see that the "hv-fcopy-daemon.service" is loaded but in a failed state. The other Hyper-V services and XRDP service are running on the VM.

On my host machine I am running Windows 10 Insiders build 17107

![image](https://user-images.githubusercontent.com/1243172/36935969-a63ce8c6-1ef6-11e8-850f-0c9590b1eb56.png)

**Comment by halldorh** [comment]
I'm running 17112 and it behaves in the same way. That is, same service is in failed state and no enhanced session.

**Comment by cwilhit** [comment]
Thanks for opening this, I'll see if I can repro on the latest insider build.

**Comment by cwilhit** [comment]
The latest commit should fix your issues. I ran a clean install with 17112 and enhanced mode works.

**Comment by marfillaster** [comment]
Just ran  to this issue. Fresh install today.

**Comment by jaguarsdv** [comment]
Does anyone can logoff, reboot, shutdown guest ubuntu in enhanced mode?

**Comment by jaguarsdv** [comment]
After I twice click logoff, guest is disconnect. When I try to reconnect, I receive this error:
![image](https://user-images.githubusercontent.com/23018240/37878252-a39f3e50-306e-11e8-95a1-36435cd7667d.png)

**Comment by jaguarsdv** [comment]
If I connect to guest ubuntu without enhanced mode and restart xrdp service, I can connect with enhanced mode with any problems, but I am worry about memory consumption, 5G on a clear install without any additional software:
![image](https://user-images.githubusercontent.com/23018240/37878444-44f189a4-3072-11e8-8759-faf4eaecadbc.png)

**Comment by jterry75** [comment]
@jaguarsdv - The logout issue is known. It appears that the Unity experience doesn't allow this well. I will try to see if there are any workarounds.

The memory usage seems more like a `Dynamic Memory` issue to me than an `Enhanced Session` issue. In your `Settings` for the VM disable DM and set a memory size that makes sense for your application.
