### ISSUE TITLE
login successfully for display 10 started... giving up some problem

### ISSUE THREAD

**Issue by WhisperingChaos** [microsoft/linux-vm-tools#101]
Similar to: #87

Ubuntu Release: 18.04.3
Linux Kernel: 5.0.0-37-generic

- Install instance of Ubuntu 18.04.3 via locally running version of Hyper-V in Windows 10.
- Download and manually run ```install.sh```.
- Update /etc/xrdp/xrdp.ini not to use ```vsock``` - ```use_vsock=false```.  This permits network access to host's (VM's) standard xrdp port.
- Connect to VM from another windows host on same LAN using its installed RDP client.

XRPD login screen appears.  Able to enter username and password.  Logon dialog box disappears leaving only blue background.  After a couple minutes  Receive following output:

```
login successfully for display 10
started connecting
connection problem, giving up
some problem
```

Noticed I needed HWE support due to kernel update which occurred in 18.04.2. Changed ```./install.sh``` HWE environment variable value so it reflected: ```HWE="-hwe-18.04"```.  However, problem above persisted.

Located [solution](https://askubuntu.com/questions/1166568/remote-desktop-blue-screen-after-login) and added following package ```xorgxrdp-hwe-18.04``` install after ```apt install -y xrdp```:
 ```
apt install -y xrdp
apt install -y xorgxrdp-hwe-18.04
```
After reboot, was able to successfully connect to the VM.

I forked the repository and have encoded a solution that works for GA and HWE installs.  The solution just needs to know the GA kernel version.  If you're interested, let me know and I'll issue a pull request.
        

.

**Comment by skywind3000** [comment]
I met the same problem, and this worked for me.

Why not include `apt install -y xorgxrdp-hwe-18.04` in `install.sh` ??

**Comment by Silavin** [comment]
> I met the same problem, and this worked for me.
> 
> Why not include `apt install -y xorgxrdp-hwe-18.04` in `install.sh` ??

Tried that but the package has already been installed.
(I'm trying to do this through the quick create).

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
