### ISSUE TITLE
HWE support package name convention

### ISSUE THREAD

**Issue by WhisperingChaos** [microsoft/linux-vm-tools#102]
[Kernel Hardware Enablement](https://wiki.ubuntu.com/Kernel/LTSEnablementStack) (HWE) support might change with each point release of Ubuntu and although one may encode the Ubuntu release as part of the actual package name, the name used to install the HWE package flavor should not include any portion of Ubuntu's release label.  Why not?  Since install scripts couple to the repository (_public_) package name, using the actual name as the repository package name will require changes to HWE aware install scripts in response to changes in other HWE components that it relies on.  For example, the HWE environment variable found in  [install.sh](../blob/aefd66c/ubuntu/18.04/install.sh#L14) would have to change to reflect its dependence on the kernel version included by the Ubuntu point release. To avoid this deadly coupling, I would suggest leveraging the level of indirection inherent in the organization of a distro's package repository, just as the General  Availability (GA) packages do. 

Install scripts for GA releases don't have to use a package's actual name.  For example, to install the```xrdp``` package on 16.04, the operator issues the command ```apt install xrpd``` the exact same command applies to 18.04.  However, these commands install different versions of ```xrdp```.  Different versions (packages) can share the same name because the distro's package repository provides a level of indirection enabling a repository package name to bind to a different package.   HWE package names could be similarly assigned.

Each HWE aware package name could be assigned a repository package name generated from its GA package name which includes some generic HWE qualifier.  For example: the GA package name ```xrdp``` can be suffixed with ```xrdp-hwe``` to differentiate it as the HWE package flavor of ```xrdp```.  Then for each HWE point release, the actual package name  ```xrdp-hwe-18.04.2``` can be bound to the ```xrdp-hwe``` repository package name.  Since the HWE repository package name remains the same, just like its GA name, code that relies on this repository name need not change.  This behavior **assumes** a distribution's package repositories are configured for each point release.  

Unfortunately, I'm not a package repository expert, so I'm not confident that the behavior above can be leveraged to eliminate deadly name coupling.

Finally, if a generic HWE repository package name cannot be realized then I would suggest including Ubuntu's entire release designation (including its point qualifier), as both the actual name and repository package name.  This facilitates coordinating HWE packages with other HWE affected packages for a specific Ubuntu point release.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
