### ISSUE TITLE
Manjaro: Cannot compile rdpInputMouse 

### ISSUE THREAD

**Issue by PatrickGoettsch** [microsoft/linux-vm-tools#104]
Hello,
I tried to install the linux-vm-tools on a manjarow guest system with xfce4 and get after a while running the makepkg.sh an error called:
WM_Button8UP not declared did you mean WM_BUTTON7UP
The same for WM_BUTTON8DOWN, WM_BUTTON9UP and WM_BUTTON9DOWN. Then it says 
[Makefile:458: rdpMouse.lo] Error 1
[Makefile:427: all-recursive] Error 1
[Makefile:359: all] Error 2

How can I solve this issue?
Thanks

**Comment by MathieuMorrissette** [comment]
I'm having the same issue. I think the AUR package isn't maintained anymore.

**Comment by acecase** [comment]
Same here. Looks like a problem with xrdp from aur.

**Comment by MathieuMorrissette** [comment]
I think this pull request fixes the issue :
https://github.com/microsoft/linux-vm-tools/pull/103

**Comment by dallasyoung** [comment]
@MathieuMorrissette I was having this same issue with a fresh Arch install as well, and https://github.com/microsoft/linux-vm-tools/pull/103 fixed it for me

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
