### ISSUE TITLE
video remoting was disconnected on Ubuntu 18.04.3 Quick Create

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/linux-vm-tools#105]
I did create ubuntu 18.04.3 on hyper-v with quick create built-in ubuntu 18.04. 
After installation, I got display size confirmation or something then I clicked OK that, the xorg login screen appeared, so I did enter login info of the ubuntu machine, and I got `video remoting was disconnected` `the session was disconnected` error popup. 

I heard solution of this, turn off auto-login on the installation step of Ubuntu, so I tried that as well, but same I got error. 

Besides, If I turn off enhanced session, I can login but after login, I couldn't almost anything. I couldn't drag window, couldn't open terminal, couldn't send shortcut key (e.g. ctrl-alt-T).

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
