### ISSUE TITLE
openSUSE VM on Windows 10 cannot have a native resolution higher than 1024x768

### ISSUE THREAD

**Issue by zlatko-michailov** [microsoft/linux-vm-tools#107]
Hi,

This issue isn't about XRDP. It is about the Hyper-V video driver. It is probably not your area, but I'm hoping you guys have dealt with it. If not, I'll appreciate it if you can hook me up with the right Microsoft team.

Here's my setup: I am running an openSUSE (Tumbleweed) VM on my Windows 10 laptop. I am connecting through the native Virtual Machine Connection. The problem is that I cannot bring the resolution above 1024x768.

I suspect the Linux kernel queries the Hyper-V video driver, and it firmly responds that no higher resolution is supported. For instance,
```
xrandr  --screen 0 --fb 1600x1200
```
produces:
```
xrandr: screen cannot be larger than 1024x768 (desired size 1600x1200)
```

So, is there any way to force an override of that maximum?

P.S. I used to use XRDP. I've set it up twice - the process is not easily reproduceable. It takes some trial-and-error. Then, every time I want to connect, it never works until I log in natively first.

**Comment by zlatko-michailov** [comment]
I am reading your wiki, and I notice this screenshot - https://raw.githubusercontent.com/Microsoft/linux-vm-tools/master/wiki/media/vmconnect.PNG. That's pretty much what I'm looking for. How did you make the Ubuntu VM offer the user to chose a resolution?

**Comment by stefanjarina** [comment]
In case anyone is reading this now and is wondering about how to get it working in openSUSE, I just submitted pull request for it with working script: https://github.com/microsoft/linux-vm-tools/pull/128

It is for Tumbleweed, but should work with Leap as well, but I did not test it yet, will get to it during Christmas

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
