### ISSUE TITLE
Enhanced session not available on Ubuntu 20.04

### ISSUE THREAD

**Issue by agilleyrh** [microsoft/linux-vm-tools#111]
Using the 18.04 script manually the output is:

Job for xrdp.service failed because the control process exited with error code.
See "systemctl status xrdp.service" and "journalctl -xe" for details.
Install is complete.
Reboot your machine to begin using XRDP.
 
sudo systemctl status xrdp
● xrdp.service - xrdp daemon
     Loaded: loaded (/lib/systemd/system/xrdp.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-04-24 12:06:03 EDT; 1min 17s ago
       Docs: man:xrdp(8)
             man:xrdp.ini(5)
    Process: 5558 ExecStartPre=/bin/sh /usr/share/xrdp/socksetup (code=exited, status=0/SUCCESS)
    Process: 5566 ExecStart=/usr/sbin/xrdp $XRDP_OPTIONS (code=exited, status=1/FAILURE)
 
Apr 24 12:06:03 uvm systemd[1]: Starting xrdp daemon...
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[INFO ] address [0.0.0.0] port [3389] mode 3
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[INFO ] listening to port 3389 on 0.0.0.0
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[ERROR] trans_listen_address failed
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[DEBUG] Closed socket 7 (AF_VSOCK cid -1 port -1)
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[ERROR] Failed to start xrdp daemon, possibly address already >
Apr 24 12:06:03 uvm systemd[1]: xrdp.service: Control process exited, code=exited, status=1/FAILURE
Apr 24 12:06:03 uvm systemd[1]: xrdp.service: Failed with result 'exit-code'.
Apr 24 12:06:03 uvm systemd[1]: Failed to start xrdp daemon.
 
Apr 24 12:06:03 uvm systemd[1]: Stopped xrdp session manager.
Apr 24 12:06:03 uvm systemd[1]: xrdp-sesman.service: Failed with result 'exit-code'.
Apr 24 12:06:03 uvm xrdp-sesman[5557]: (5557)(139991032587840)[DEBUG] Closed socket 7 (AF_INET6 ::1 port 3350)
Apr 24 12:06:03 uvm xrdp-sesman[5557]: (5557)(139991032587840)[INFO ] shutting down sesman 1
Apr 24 12:06:03 uvm systemd[1]: xrdp-sesman.service: Control process exited, code=exited, status=1/FAILURE
Apr 24 12:06:03 uvm sudo[2047]: pam_unix(sudo:session): session closed for user root
Apr 24 12:06:03 uvm systemd[1]: Stopping xrdp session manager...
Apr 24 12:06:03 uvm systemd[1]: Failed to start xrdp daemon.
Apr 24 12:06:03 uvm systemd[1]: xrdp.service: Failed with result 'exit-code'.
Apr 24 12:06:03 uvm systemd[1]: xrdp.service: Control process exited, code=exited, status=1/FAILURE
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[ERROR] Failed to start xrdp daemon, possibly address already >
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[DEBUG] Closed socket 7 (AF_VSOCK cid -1 port -1)
Apr 24 12:06:03 uvm kernel: NET: Registered protocol family 40
Apr 24 12:06:03 uvm kernel: hv_vmbus: registering driver hv_sock
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[ERROR] trans_listen_address failed
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[INFO ] listening to port 3389 on 0.0.0.0
Apr 24 12:06:03 uvm xrdp[5566]: (5566)(140435497408320)[INFO ] address [0.0.0.0] port [3389] mode 3
Apr 24 12:06:03 uvm xrdp-sesman[5557]: (5557)(139991032587840)[INFO ] listening to port 3350 on 127.0.0.1
Apr 24 12:06:03 uvm systemd[1]: Starting xrdp daemon...
Apr 24 12:06:03 uvm systemd[1]: Started xrdp session manager.
Apr 24 12:06:03 uvm xrdp-sesman[5557]: (5557)(139991032587840)[INFO ] starting xrdp-sesman with pid 5557
Apr 24 12:06:03 uvm xrdp-sesman[5556]: (5556)(139991032587840)[DEBUG] Closed socket 5 (AF_INET6 ::1 port 3350)
Apr 24 12:06:03 uvm xrdp-sesman[5556]: (5556)(139991032587840)[DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 >
Apr 24 12:06:03 uvm xrdp-sesman[5556]: (5556)(139991032587840)[DEBUG] libscp initialized
Apr 24 12:06:03 uvm systemd[1]: Starting xrdp session manager...
Apr 24 12:06:03 uvm systemd[1]: /lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy direc>
Apr 24 12:06:03 uvm systemd[1]: Reloading.
Apr 24 12:06:03 uvm systemd[1]: Stopped xrdp session manager.
Apr 24 12:06:03 uvm systemd[1]: xrdp-sesman.service: Failed with result 'exit-code'.
Apr 24 12:06:03 uvm xrdp-sesman[4470]: (4470)(140574392751680)[DEBUG] Closed socket 7 (AF_INET6 ::1 port 3350)
Apr 24 12:06:03 uvm xrdp-sesman[4470]: (4470)(140574392751680)[INFO ] shutting down sesman 1
Apr 24 12:06:03 uvm systemd[1]: xrdp-sesman.service: Control process exited, code=exited, status=1/FAILURE
Apr 24 12:06:03 uvm systemd[1]: Stopping xrdp session manager...
Apr 24 12:06:03 uvm systemd[1]: Stopped xrdp daemon.
Apr 24 12:06:03 uvm systemd[1]: xrdp.service: Succeeded.
Apr 24 12:06:03 uvm xrdp[4490]: (4490)(140142919702336)[DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
Apr 24 12:06:03 uvm systemd[1]: Stopping xrdp daemon...
Apr 24 12:06:00 uvm xrdp[4490]: (4490)(140142919702336)[INFO ] xrdp_listen_pp done
Apr 24 12:06:00 uvm xrdp[4490]: (4490)(140142919702336)[INFO ] listening to port 3389 on 0.0.0.0
Apr 24 12:06:00 uvm xrdp[4490]: (4490)(140142919702336)[INFO ] address [0.0.0.0] port [3389] mode 1
Apr 24 12:06:00 uvm xrdp[4490]: (4490)(140142919702336)[INFO ] starting xrdp with pid 4490

**Comment by indolering** [comment]
See [fix here](https://github.com/microsoft/linux-vm-tools/pull/106).

**Comment by agilleyrh** [comment]
Running the script in that commit and a few reboots of the VM and host seem to have finally fixed it 👍 Thanks!

**Comment by abraxxa** [comment]
Please reopen the issue because the linked fix is still not merged and the Ubuntu 20.04 from the VM quick creation also doesn't work with enhanced session out of the box. Thanks!

**Comment by styxptyx** [comment]
After working for several hours on solving this problem, here is a solution that works (at least for me).
My background: RDP client on Windows 10, Ubuntu 20.04 server.
Edit the file /etc/xrdp/xrdp.ini
Modify the parameters as follows :
port = tcp: //: 3389
use_vsock = true
Then restart the xrdp service: sudo systemctl start xrdp
(don't forget to allow port 3389 in the ufw firewall if in use)

**Comment by abraxxa** [comment]
For me both Ubuntu 20.10 from the VM gallery or what it's called and a manually installed Ubuntu 20.10 work when running the 20.10 script from the linked pull request.

**Comment by iancward** [comment]
I to set `port = tcp: //: 3389` as above, but had to set `use_vsock = false` in order for it to work.
