### ISSUE TITLE
missing support for Ubuntu LTS 20.04

### ISSUE THREAD

**Issue by ophirharran** [microsoft/linux-vm-tools#112]

**Comment by koldat** [comment]
I have installed 20.4 and then used 18.04 script. Then I have to change in /etc/xrdp/xrdp.ini:
```
port=vsock://-1:3389
use_vsock=false
```

It works after that.

More details #94

**Comment by ophirharran** [comment]
> I have installed 20.4 and then used 18.04 script. Then I have to change in /etc/xrdp/xrdp.ini:
> 
> ```
> port=vsock://-1:3389
> use_vsock=false
> ```
> 
> It works after that.
> 
> More details #94

Hey, I followed your advice but am unable to use enhanced session or xrdp, what am I missing?

**Comment by koldat** [comment]
Have you executed this in powershell? That is all I did. Just look at manual install wiki. 

Set-VM -VMName <your_vm_name> -EnhancedSessionTransportType HvSocket

**Comment by ophirharran** [comment]
Yes I have, and everything worked well for 18.04 Ubuntu I tried. so frustrated

**Comment by koldat** [comment]
There is a pull request for 20.4 as well #106. You can try it. Also you need to be more specific what does not work if you need help.

**Comment by ophirharran** [comment]
I appreciate your help. I am also using fresh install. gave on update before.
to specify my problem better, I am able to connect via hyper-v console but the performance is low as expected and can't use full-screen.
On 18.04 when I connect to the machine the xrdp teal screen comes up and everything works fine from there. in contrast, on 20.04, the xrdp teal screen is not showing.

will look at #106 you suggested in the meantime. any other suggestions?

**Comment by koldat** [comment]
I did:
1. Install
2. Login, sudo, git clone, install, restart
3. Install, restart
4. Shutdown, powershell
5. Fixed config file. Restart
6. It started working

The ugly login means it works. Nice login it does not. I also see red error during boot (caused by that config error). In issue I referenced there is a command for listing log for xrdp so you can see what is a problem.

**Comment by ophirharran** [comment]
it worked!
i did a fresh install, used the script from #106 as-is, turn-off, powershell, turn-on.

Thanks a lot, @koldat!
