### ISSUE TITLE
directly support X2Go style connection in lieu of XRDP

### ISSUE THREAD

**Issue by trailstrider** [microsoft/linux-vm-tools#118]
X2Go's X over SSH to a VM seems to be a much more robust approach to getting screen size customization working.  Also more secure.  Would be nice to expand upon these capabilities for direct support in Hyper-V, and by extension get them working in the cloud too.  A lot could also be done with an SSH key CA, to make this even more secure and portable across domains.

FWIW, [Keybase solved SSH key centralization in a great way](https://keybase.io/blog/keybase-ssh-ca), and of course that development has changed now that they've been bought by Zoom.  Would love to see MS Teams make enterprise ssh keys a reality, so that this becomes yet another feature that benefits.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
