### ISSUE TITLE
Shared drivers readonly: weird behavior

### ISSUE THREAD

**Issue by daitangio** [microsoft/linux-vm-tools#119]
Hi on Windows 10 [10.0.19041.329] I was able to activate enhanced session on Ubuntu 18 but shared drives do not work properly.
I can write file on a shared drive but I cannot edit it anymore:

```bash
jj@eva01:~/shared-drives/C:/temp$ uname -a
Linux eva01 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
jj@eva01:~/shared-drives/C:/temp$ echo "Test1">test.txt
jj@eva01:~/shared-drives/C:/temp$ echo "Test2">>test.txt
bash: echo: write error: Input/output error
jj@eva01:~/shared-drives/C:/temp$ 
```

Printer sharing is disabled.
How can we fix the problem ?

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
