### ISSUE TITLE
How to reset/change settings saved on the first login

### ISSUE THREAD

**Issue by SasukeeUchiha** [microsoft/linux-vm-tools#120]
How do you change or remove the settings saved on the first login? I want to change drives that are shared?

**Comment by DonneyF** [comment]
You can try right-clicking the VM and clicking `Edit Session Settings...`

or you can run this from Powershell to bring up the prompt again. `vmconnect localhost <VM_NAME> /edit` If your VM name has spaces in it you'll need to wrap it in quotations, like `vmconnect localhost "Ubuntu 20.04 LTS" /edit`.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
