### ISSUE TITLE
Mouse side-buttons (8+9) fire twice once linux-vm-tools installed

### ISSUE THREAD

**Issue by Giraffaman** [microsoft/linux-vm-tools#121]
Hi,

I was testing in a Hyper-V VM and noticed that, once enhanced session is active, the side-buttons (forward/back) on my mouse consistently fire twice on a single click, causing e.g. Firefox to go back/forward by two pages instead of one. I checked with xinput test and xev which both show that with each click, I see a buttonPress and buttonRelease event for button 8/9 on mousedown and mouseup respectively.

Was able to reproduce this issue on Ubuntu 18.04.4, Ubuntu 20.04 and Pop_OS 20.04 - once enhanced session is deactivated and the VM is restarted, the issue disappears. 

I'm not sure whether this is caused by one of the linux-tools packages or by xorgxrdp, so please forgive me if I'm reporting this in the wrong place here.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
