### ISSUE TITLE
Path problem

### ISSUE THREAD

**Issue by ljy-002** [microsoft/linux-vm-tools#125]
I installed Hyper-V and set the path of the H drive, but the C drive is still occupied
![image](https://user-images.githubusercontent.com/63292034/90362978-5db2c500-e094-11ea-8cea-36665d6a6d23.png)

**Comment by ljy-002** [comment]
![image](https://user-images.githubusercontent.com/63292034/90363008-6dcaa480-e094-11ea-88a9-3acd227b5b3c.png)

**Comment by ljy-002** [comment]
![image](https://user-images.githubusercontent.com/63292034/90363720-c484ae00-e095-11ea-92b3-09bf73a6b4d1.png)

**Comment by ljy-002** [comment]
![image](https://user-images.githubusercontent.com/63292034/90363840-f1d15c00-e095-11ea-8fcf-a81fbad1c48f.png)

**Comment by MapMaths** [comment]
Actually, System use C: to work. the system files and start menus are in C:, so as it is needed, it has to use this space

**Comment by ljy-002** [comment]
<img width="189" alt="6481C0DA-07F3-438e-A83D-CFA8301505F0" src="https://user-images.githubusercontent.com/63292034/90399433-81463180-e0cd-11ea-9550-a31abf65b64f.png">

**Comment by ljy-002** [comment]
> Actually, System use C: to work. the system files and start menus are in C:, so as it is needed, it has to use this space

Yes, but why does Microsoft always use the C drive, if I change to the Apple system?

**Comment by MapMaths** [comment]
You can change it, actually, but I don't suggest you to, in the settings

**Comment by ljy-002** [comment]
> 实际上，您可以在设置中进行更改，但我不建议您进行更改



> You can change it, actually, but I don't suggest you to, in the settings

**Comment by ljy-002** [comment]
> You can change it, actually, but I don't suggest you to, in the settings

But I hope to know where to change, thank you
