### ISSUE TITLE
No xrdp connection on 16.04.7

### ISSUE THREAD

**Issue by gc435** [microsoft/linux-vm-tools#126]
- Installed Ubuntu 16.04 from the Quick Create gallery
- Did not enable auto-login
- `sudo apt ugrade ; sudo apt update`.  Rebooted.  Now I have Ubuntu 16.04.7 as reported by `lsb_release -a`.
- Followed the [onboarding instructions for manual installation on Ubuntu 16.04](https://github.com/Microsoft/linux-vm-tools/wiki/Onboarding:-Ubuntu)
- Rebooted as prompted
- Set Enhanced Mode in a PowerShell terminal running as Administrator

When I do the above, I still see a regular Ubuntu login screen.  I do not see the xrdp screen and cannot change the resolution.

1. I see fixes for 16.04.3 mentioned in `install.sh`.  Could there be additional fixes required for later releases such as 16.04.7?
2. How can I troubleshoot this?

**Comment by black2996** [comment]
Encounterd the same, maybe you can get some clues from xrdp logs. I switched to bionic, ESM worked well with a fresh quick-gallery installation.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
