### ISSUE TITLE
16.04 - Configuration / Login Issue

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/linux-vm-tools#15]
Not urgent as I just wanted to try out the experience.

I followed the instructions listed here https://blogs.technet.microsoft.com/virtualization/2018/02/28/sneak-peek-taking-a-spin-with-enhanced-linux-vms/ 

I see the default xrdp login prompt:

![image](https://user-images.githubusercontent.com/616249/37566973-204e822e-2ab8-11e8-828d-5f2d76f1294a.png)

No login details work; if I disable the enhanced session then it drops back to normal shell and I can use as before.

Let me know if there's anything else you want me to try and send to help before official launch

**Comment by jterry75** [comment]
Does it give you any more information in the failure context? Also you could check `/var/log/xrdp.log` and `/var/log/xrdp-sesman.log` for any extended error info why the session failed.

**Comment by dankseman** [comment]
There is a bug in the login. I created a user called M (upper case) and it would not login in.  I discovered by trial and error I had to use lower case m.

Without further testing, I do not know if you have to enter it all as lower case or reverse the case e.g.

Mike ---->  mike  or  mIKE

**Comment by johnkattenhorn** [comment]
@jterry75 - I'll try to grab those details when I'm back in my office at the end of the week; @dankseman  -I wonder if that's my issue - I'm pretty sure Login is Installer in the machine I was trying.

**Comment by johnkattenhorn** [comment]
@dankseman - I had to use all lower case but it worked for me, the experience is awesome.

**Comment by johnkattenhorn** [comment]
@jterry75 - No errors apparent in either of those files and it works if I login, is the current user experience to see the xorg login screen as I screenshotted above ?

**Comment by dankseman** [comment]
Can you see pc drives - it does not work for me.

**Comment by johnkattenhorn** [comment]
@dankseman - not working for me either; I see this 

![image](https://user-images.githubusercontent.com/616249/37864957-9e4a075c-2f6d-11e8-8a55-e0e7bea33628.png)

**Comment by dankseman** [comment]
You have to select drives to see from the enhanced config screen that
popups up to set resolution.

I get the drives listed but no details.

**Comment by dankseman** [comment]
Log it on exist github comments.

Until this is fixed enhanced  option is pretty useless apart from cut and
paste.

Real disappointment is no sound.

**Comment by Fabyao** [comment]
I know this is beta software and is not meant for ubuntu 16.04. However performance was poor. Opening apps and visual effects are painfully slow. Have I missed something? @dankseman, I can personally see past the sound but not the performance. I am by no means an expert in virtualization. I dont understand why RDP protocol is used to gain access to a virtual machine? How can one implement hardware acceleration through RDP? Hopefully the final release on ubuntu 18.04 will be better. I had hight hopes with HyperV as WSL is also unusable  [Slow IO performance WSL ](https://github.com/Microsoft/WSL/issues/873).

**Comment by dankseman** [comment]
The xrdp should not affect performance of the vm.  It only adds some extra
interfacing eg drives (not working properly), access to pc clipboard etc.
that you do not get in basic Hyper-V mode.

**Comment by cwilhit** [comment]
We're tracking the drive mounting issues in a separate issue #6 .

@Fabyao - how much resources ( vCPUs and memory) are you allocating to the VM? Describing the experience as "painfully slow" has not been my experience, so something must be aloof :)

@dankseman using the RDP protocol does indeed affect the user-perceived performance of the VM. Since it is it's own protocol with it's own implementation for encoding/decoding. See for yourself - go look at the webgl aquarium sample in enhanced mode vs basic mode.

**Comment by dankseman** [comment]
Without this working, the enhanced mode is pretty useless.  You can set
screen sizes easily enough by editing config files.  The only plus then is
cut and paste but that is all.

With easy disk access and SOUND, then this would be great. Until the Linux
in Hyper-V is a poor experience compared with vmware etc.

**Comment by Fabyao** [comment]
@cwilhit Thank you for your reply. I have allocated 4 CPUs and 8GB of Ram I also tried with RemoteFX 3D Adapter. A simple mouse over effect is delayed by about 3 seconds. Dragging windows is also lagging. I agree with @dankseman that VMWare has better performance/ user experience. No lags at all. As mentioned before I am no virtualization expert but I am not convinced that adding yet another layer (XRDP) is a good idea. This is based on my experience with VMWare and [Open VM Tools](https://github.com/vmware/open-vm-tools). I appreciate VMWare might be based on a different architure, however you might find the source to be of interests.

**Comment by Fabyao** [comment]
@cwilhit Sorry I forgot to mention that this is running the enhanced session in full screen mode on a Surface Book 2 with 16GB Ram Corei7. Looking forward to test the final release with Ubuntu 18.04.

**Comment by dankseman** [comment]
I think I may have slightly mislead here.  I called my PC D, and set up user as d as usernames have to be in lower case on 1804.

**Comment by cwilhit** [comment]
Closing issue because it appears to have become stale. We'll track any general perf feedback on #28
