### ISSUE TITLE
Split into multiple modules

### ISSUE THREAD

**Issue by Thaodan** [Microsoft/linux-vm-tools#20]
Currently the script is build for each distro, but most of the stuff could be distro in-depend.
So I ask is it intended the script is always a single file or would it be ok if the script would consist of multiple files that are sourced?

**Comment by cwilhit** [comment]
The thinking behind the script's intent was to give the community a way to begin trying out a better experience for Ubuntu guests in Hyper-V--something for the community take inspiration from, run with, and do however they'd like (it being a simple single file accomplished that easily).
