### ISSUE TITLE
Enhanced Session Mode Supports Autologin

### ISSUE THREAD

**Issue by oldium** [microsoft/linux-vm-tools#22]
Hi, just to inform you that I had problem with auto-login in Ubuntu 16.04. I used a user with auto-login enabled, so when I started the VM, it automatically logged the user in. I then tried to use the enhanced session, but when I logged in (I used session `Xorg`) and tried to launch Terminal application (which I pinned to panel from normal session some time before), I saw strange crashes inside VM and later the Windows host froze itself. When I disabled auto-login in /etc/lightdm/lightdm.conf, the enhanced session login went fine and I saw no crashes (I saw a send-problem dialog, but it did not influence the work - maybe some earlier crash).

Same with Ubuntu 18.04 beta 2 (Desktop installation, minimal version), where I do not know how to disable the auto-login. Maybe I will try to install it once again, but now with auto-login disabled.

**Comment by jterry75** [comment]
Hey, thank you for the feedback. What are you expecting to happen in this scenario? The autologin is for the X11 monitor `:0`. Which VMConnect displays as the 'Basic Session'. When you create the enhanced session xrdp creates a new X11 Session starting (typically) at monitor `:10`. So this account needs to `acl` the user trying to connect. I'm not sure we can do much better than this. I will follow up with some people at Canonical and see if they have any ideas.

**Comment by oldium** [comment]
Linux usually does not have any issues with the same user logged-in into multiple X sessions. I would expect that when the user is auto-logged to the native X session, the Enhanced Session is able to log in without any issues too - having the user logged-in twice in fact (once in native X, once Enhanced Session - RDP). Enhanced Session login should be independent on what is happening in other user sessions on the Linux machine.

**Comment by astein70** [comment]
With Windows 1803 latest preview taken yesterday, version 17134.5, I was stuck on the xRdp logon page using session Xorg , finally corrected by following dankseman's thought above and not auto-logging in my id.  Unfortunately I could not unlock my id to stop auto-logon for some reason, so did a reinstall of 18.04.

**Comment by giggio** [comment]
I can confirm the problem with autologin.
I had to disable Enhanced VM Support on HyperV to be able to get back to the machine, then I edited the `/etc/gdm3/custom.conf` file and removed autologin (it would not allow me to do it through the account settings window from Gnome).
After that I shut the VM down, reenabled Enhanced mode for the server, and I was able to use enhanced mode with Ubuntu.
I am on Windows 10 1803 stable and Ubuntu 1804 stable.

**Comment by sundhaug92** [comment]
Same here. I'd suggest modifying the installer to disable autologin

**Comment by giggio** [comment]
@cwilhit Why was this closed? Is it fixed?

**Comment by cwilhit** [comment]
No, auto-login will not work withe enhanced session mode. So, current recommendation is to disable auto-login. Reopening and tagging as "feature" to track req.

**Comment by oldium** [comment]
What about pam_xauth? It looks like it could do the trick. Execute the following:

```
grep pam_xauth /etc/pam.d/xrdp-sesman || echo "session optional pam_xauth.so" >>/etc/pam.d/xrdp-sesman
```

And... Enjoy even with autologin enabled. Tested with Ubuntu 16.04 LTS.

**Comment by oldium** [comment]
Have anybody tried to add the line `session optional pam_xauth.so` to `/etc/pam.d/xrdp-sesman` as described above? I would like to know if it works just for me or also others, so I could prepare a pull request to update the installation steps.

**Comment by dankseman** [comment]
I will give it a crack but still not certain it will work reliably as
Hyper-V does not even like Windows autologging in - it seems to get in a
tizzy starting new sessions.

**Comment by oldium** [comment]
This particular issue has nothing to do with Hyper-V, you would have the same issue on normal PC with Linux. Sharing the xauth token (from running X session) is necessary when you are already logged-in.

**Comment by dankseman** [comment]
I think you miss my point - Hyper-V gets tangled up when you try to
autologin - nobody has ever been able to start a hyper-v session using any
OS that I am aware, without hyper-v usually throwing a fit.  It just gets
in a loop restarting new sessions BUT occasionally works - so there seems
to be a timing issue somewhere.  I will try it though.

**Comment by oldium** [comment]
I understand your point, but this is Linux and it has different culprits. This is not magic, Hyper-V just tries to connect to the virtual machine via Remote Desktop connection, which is on Linux handled by started XRdp. So at the end you need to solve problem of running one X session (auto logged-in user) and another X session for the same user, but started from XRdp. When you try to play with multiple X sessions on Linux, you need to play also with xauth tokens and this is why I tried pam_xauth, which shares xauth between logins.

**Comment by shadowx360** [comment]
> What about pam_xauth? It looks like it could do the trick. Execute the following under user `root`:
> 
> ```
> grep pam_xauth /etc/pam.d/xrdp-sesman >/dev/null || echo "session optional pam_xauth.so" >>/etc/pam.d/xrdp-sesman
> ```
> And... Enjoy even with autologin enabled. Tested with Ubuntu 16.04 LTS.

Not working on Ubuntu 18.04.1 LTS as created via Quick Create. I executed that as root, restarted VM, and on login via enhanced session, same issues appears where xrdp just crashes.

**Comment by oldium** [comment]
I will try it this week as the time permits.

**Comment by oldium** [comment]
Indeed, there is something seriously broken in 18.04. The release by itself looks broken (like switching of keyboard mapping does not work without updating). Maybe the problem is caused by Wayland, but even when I [disabled it](https://linuxconfig.org/how-to-disable-wayland-and-enable-xorg-display-server-on-ubuntu-18-04-bionic-beaver-linux), it did not help. Somebody with more knowledge on this is needed... :-( Anyway, a first-class-citizen for Ubuntu on Windows 10 as promised does not happen obviously...

**Comment by sundhaug92** [comment]
@oldium Is this a fresh 18.04 VM? 18.04 uses Xorg by default

**Comment by oldium** [comment]
@sundhaug92 Definitely, new one - I created it in the morning and now let it run for a while without "Enhanced session" to enable pam_xauth as mentioned above. I also installed updates (they prompted after several minutes), without them the Ubuntu experience was broken (like mentioned keyboard layout switching). Auto-login enabled, pam_xauth in place, but xrdp server crashes when you try to login. Wayland was just an idea, I am not sure whether it was actually was running, but definitely with it disabled it did not make any difference.

**Comment by porkstoners** [comment]
> /etc/gdm3/custom.conf

This worked for me just had to set the 

`AutomaticLoginEnable=false
`

**Comment by oldium** [comment]
@porkstoners That is just a workaround. Trick with passing xauth tokens should fix the issue independently on AutoLogin status.

**Comment by jjbailey** [comment]
Here's some feedback on Arch testing:

1) I'm in the same camp as other people who would like to bypass the session manager prompts and just autologin.
2) Audio can be good on some sites and quite late on other sites.  Examples: cbsnews' A/V sync is pretty good; youtube's audio is visibly and annoyingly late.
3) If the host goes into sleep mode, one must reconnect to the guest.  The session resumes where it left off, but audio is dead and it seems nothing can be done to revive it short of rebooting the guest.
4) Overall, performance is very good.

**Comment by lythix** [comment]
This should be listed as a Bug, not a Feature. The default for the new Quickstart Ubuntu 18.04.1 image is to have Autologon set to on, and it currently does not work. 
Wasted an hour on this trying to get it to fullscreen and setting Autologon to off is a workaround. The bug needs to be made more visible seeing that it is the default.

**Comment by oldium** [comment]
I had a look at the issue of failed logins and found out that pam_xauth is failing (I added a `debug` option to `pam.d`). The following is in the `auth.log` log:

```
user has no DISPLAY, doing nothing
```

That means that pam_xauth is not doing anything, because simply the DISPLAY environment variable is not set in the xrdp session. There has to be some difference in the startup of 16.04 and 18.04, hopefully somebody finds the root cause.

**Comment by oldium** [comment]
Hm. Strange is that on my old 16.04 the pam_xauth is not used and Enhanced Session is able to login even when being logged-in with the same user already...

**Comment by oldium** [comment]
Newest git master of xrdp on 18.04 still fails to start when the user is logged in (without and with pam_xauth - same error) - I tried compilation from 16.04 script (new package pkg-config needed to be installed), I just removed 16.04-specific part.

**Comment by GrungeMirkwood** [comment]
> Newest git master of xrdp on 18.04 still fails to start when the user is logged in (without and with pam_xauth - same error) - I tried compilation from 16.04 script (new package pkg-config needed to be installed), I just removed 16.04-specific part.

What is the 16.04 specific part?  I'd like to try your fix, as I'm on 18.04 and nothing above your comment has worked for me.

**Comment by SasukeeUchiha** [comment]
Did you try this in 20.04? Does 20.04 even support enhanced session yet?

**Comment by oldium** [comment]
Ubuntu 20.04 is in pull #106. It works, I am using it without auto-login.

**Comment by SasukeeUchiha** [comment]
You mean the autologin thing?

**Comment by oldium** [comment]
Yes, by autologin I mean automatic user login when Ubuntu starts-up. This does not work, I have no workaround/fix for this.

When you try it you end up with black screen in Enhanced Session. Windows opened in Basic Session start opening in Enhanced Session.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
