### ISSUE TITLE
Ubuntu 18.04 script errors with final version

### ISSUE THREAD

**Issue by JohnGalt1717** [Microsoft/linux-vm-tools#29]
rmmod: ERROR: Module vmw_vsock_vmci_transport is not currently loaded
rmmod: ERROR: Module vsock is in use by: hv_sock

The script also continues on these error cases instead of stopping.

How do I get around this?

**Comment by cwilhit** [comment]
John, those errors are not fatal and should not impact the script's workability.

**Comment by JohnGalt1717** [comment]
OK, well I don't get any response even with 3389/tcp opened on the firewall.

**Comment by cwilhit** [comment]
Are you running the 18.04 script on a fresh install of the 18.04 iso?

**Comment by JohnGalt1717** [comment]
Upgrade from 16.04 but yes, running the 18.04 script. Also tried removing xrdp and re-adding it and running the script again and it fails.

**Comment by JohnGalt1717** [comment]
Issue is that this is a server with a lot already on it that I don't want to blow up... too bad. Will continue using it the hard way.

**Comment by cwilhit** [comment]
Ok, first thing to check is what the state of XRDP is in. From a terminal, could you get the output of: "sudo systemctl status xrdp"

**Comment by jterry75** [comment]
Adding to the list of what @cwilhit is saying:

- xrdp.ini - Is this empty? Does it have all the modifications in the 18.04 script that sed is doing?
- sesman.ini - Is this empty? Does it have all the modifications in the 18.04 script that sed is doing?
- /etc/xrdp/startubuntu.sh - Does this file exist?
- /var/log/xrdp.log - Anything interesting?
- /var/log/xrdp-sesman.log - Anything interesting?

**Comment by jterry75** [comment]
I think this PR should of resolved your issues. Let me know if you you found something else.

**Comment by cwilhit** [comment]
Fix to instead blacklist these drivers has been in for a while and no movement on this thread. We believe this issue is fixed.
