### ISSUE TITLE
A Solid Start - Improvements Please!

### ISSUE THREAD

**Issue by seffyroff** [Microsoft/linux-vm-tools#32]
Hi there!

Thanks so much for your efforts so far.  The hint of a promise of a usable Ubuntu desktop for daily work running as a guest on a Windows host is compelling!

I've got a few issues that prevent me from adopting this as my new home:

1: No multi-monitor support.  If I choose 'use all my monitors' it crashes out.  Turning that off, it works.
2: Is there any hardware acceleration?  It seems like it's software rendering, or at least not getting full HW accel.  I'm running on a single monitor at 1920x1200 and I see tearing quite frequently when simply moving windows around etc.  Watching a YT video more clearly demonstrates the poor framerate,  I tried enabling a RemoteFX resource for the guest, but this made no difference (however I didn't change anything on the guest side)

3: No sound.  I don't get any.

Configuration:
Host: Win 10 Pro 1804 17134.1, Nvidia 1070 GPU, 16GB RAM, 2 monitors: 1x 1920x1200, 1x 1920x1080.  Core i7 2600K CPU (VTx support, no VTd).  Asus Sabertooth P67 mobo.
Guest config: Bionic final installed from ISO, 8GB ram allocated, 40GB storage on Host SSD drive (system drive)

**Comment by cwilhit** [comment]
Thanks for dropping by and submitting this feedback! This helps us navigate next steps with where users want us to take the feature, so this is very much appreciated.

**Comment by seffyroff** [comment]
My pleasure.  You should know that my small group of local hackers meetups have affectionately nicknamed this process 'X-Derping'.  We only give names to things we like :)

**Comment by pdeva** [comment]
i am not seeing any sound or video acceleration either.
i got a gtx 1080 card. running on 4k display with 2x scaling.

**Comment by cwilhit** [comment]
Pdeva, sound & RemoteFX are not features we worked to enable in this release. Thanks for the feedback, we'll add these requests to the list.
