### ISSUE TITLE
not seeing shared drives

### ISSUE THREAD

**Issue by pdeva** [Microsoft/linux-vm-tools#35]
running 18.04 and Windows 10, version 1803.
i can log into enhanced session but the 'shared folders' drives is empty

![image](https://user-images.githubusercontent.com/3190176/40090361-321df77e-5866-11e8-939e-32cbbf4d0cab.png)

**Comment by cwilhit** [comment]
In the enhanced connect window, do:

1. Click "show options"
2. Click "Local Resources" tab
3. Make sure printers is **unchecked**
4. Click on "More" button
5. Make sure "Drives" is checked.

These are the same steps you would do if you wanted to share local resources with a Windows VM, found [here](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/use-local-resources-on-hyper-v-virtual-machine-with-vmconnect), with the extra caveat that you need to make sure "printers" is never checked (xrdp doesn't like sharing printers).

**Comment by pdeva** [comment]
thing is now when i 'start' the vm, it directly goes to the xorg login box instead of the dialog with display configuration and 'show options'. how do i get back to that dialog?

**Comment by cwilhit** [comment]
See #34 for how to get that back. Please let me know if what I described above works so I can close this issue.

**Comment by pdeva** [comment]
tried it and its very, very buggy. now the vm can no longer shut down... 
all of this should be far more intuitive really

**Comment by cwilhit** [comment]
Please describe what is buggy. Did the shared drives that you selected appear in your Linux VM now?
