### ISSUE TITLE
Video remoting was disconnected

### ISSUE THREAD

**Issue by shadowx360** [Microsoft/linux-vm-tools#39]
I downloaded fresh Ubuntu 18.04 iso from website, followed the instructions on the wiki to the letter and after I restart, I see the Xorg login. I enter in my username and password and then it abruptly disconnects with message "Video remoting was disconnected". If I turn off Enhanced session services, I can see the Ubuntu desktop, but any attempts to launch any app besides Settings gets a spinning circle and then killed. Username and password are fine because it gives me an error if I intentionally enter wrong password.

Running on Windows 10 Enterprise 1803, all updates applied, Hyper-V gen 2 VM. Using commit 11be5b1 (42 minutes old). Wiki instructions are also the newest instructions, less than an hour old. Also tried the jterry75 install.sh as well, same results. Even tried an old post saying disabling UDP/TCP checksum offloads.

**Comment by cwilhit** [comment]
Hey @shadowx360, if you can connect onto the VM with a normal connection (non-enhanced) a few things to check:
- sudo systemctl status xrdp - What is printed here?
- /var/log/xrdp.log - What is printed here?
- /var/log/xrdp-sesman.log - What is printed here?

**Comment by sundhaug92** [comment]
You wouldn't happen to have autologin enabled? Then it's related to #22, I had a similar experience (including inability to launch terminal)

**Comment by nedotter** [comment]
I am getting the exact same issue as @shadowx360, with the current release of Ubuntu Server 18, and the most recent "Insider" version of Windows 10. Also tried with the most recent version of Windows 10 Pro, but no difference. Hyper-V gen2

Granted I'm no Linix guru, but I've been trying this for days to no avail. Also tried Ubuntu 16, same thing. 

The xrdp service is up, and I even made user part of sudu, thinking that it was perhaps a permissions issue. 

Any thoughts on next steps, @cwilhit ? 

I checked: 
systemctl status xrdp
/var/log/xrdp.log
/var/log/xrdp-sesman.log

And perhaps I don't what I'm looking at/what to look for, but answering the "What is printed here?" question is not simple, as there is a lot of verbage in those files. 

Thanks in advance for any guidance you might have.

**Comment by cwilhit** [comment]
Check your /etc/xrdp/xrdp.ini file. Is it blank?

**Comment by nedotter** [comment]
Chris - I checked that /etc/xrdp/xrdp.ini file, and it is definitely not blank - loads of stuff in there.

**Comment by nedotter** [comment]
One thing I'm not clear on, is if this functionality still requires a pre-release version of Windows 10. I'm currently running on Windows 10 Pro, version 1803.

**Comment by sundhaug92** [comment]
@nedotter 1803 supports the feature

**Comment by nedotter** [comment]
Thanks, @sundhaug92  - very frustrating beating my head against the screen for about a week now, trying to get this to work.

**Comment by sundhaug92** [comment]
@nedotter Understandable. Again, you wouldn't happen to have autologin enabled?

**Comment by nedotter** [comment]
@sundhaug92 I've never enabled it - is it enabled by default? How can I best confirm if it's enabled?

**Comment by sundhaug92** [comment]
@nedotter Then it should not be enabled. If you disable enhanced session support, do you have toi enter a username and password or does it just automatically log you in to the desktop?

**Comment by nedotter** [comment]
@sundhaug92 When I disable enhanced session support, I must supply user/pass to login.

**Comment by cwilhit** [comment]
Have you tried with Ubuntu Desktop? This is the image that we've been using and I wonder if Ubuntu Server doesn't carry some bits which might be contributing to your issue.

**Comment by nedotter** [comment]
Thanks, Chris. Will try that and report back.

**Comment by nedotter** [comment]
@cwilhit I tried with Ubuntu desktop, and it worked - thanks for the suggestion. Most humble apologies for not getting your name right in my earlier comments (now corrected).

**Comment by cwilhit** [comment]
Not an issue :) it also took me a moment to realize you were trying with Ubuntu _server_ instead of desktop. With your issue resolved, I will close this.

**Comment by matjazmav** [comment]
> You wouldn't happen to have autologin enabled? Then it's related to #22, I had a similar experience (including inability to launch terminal)

That was my problem :) Thank you!

**Comment by stevelerner** [comment]
Make sure you are logged out of Ubuntu Desktop when you use the Enhanced Session.
If you are already logged in, there seems to be some problem with logging in again with the Xorg login. 
This was the only thing that I needed to do to fix the problem- ensure I was logged out before connecting with an Enhanced Session.
