### ISSUE TITLE
"Primary Button" in "Mouse & Touchpad" options doesn't work

### ISSUE THREAD

**Issue by manofstick** [Microsoft/linux-vm-tools#41]
Windows 10 Settings -> Mouse -> Select your primary button "Right"
Hyper-V Ubuntu 18.04 -> "Mouse & Touchpad" -> Primary Button -> "Right"

But the left button is still the Primary Button. Doesn't matter what if I change it to Left.

It worked as expected prior to installing the "linux-vm-tools"

**Comment by cwilhit** [comment]
Interesting find, was able to repro on my own VM; the Microsoft Vmbus mouse device honors the setting, but xrdpMouse will not.

As a temp fix for this, you can query "xinput list" -> get the id of xrdpMouse -> run "xinput set-button-map <ID of mouse> 3 2 1"

**Comment by jterry75** [comment]
@cwilhit - Can we log this bug on xorgxrdp? Seems like a bug

**Comment by cwilhit** [comment]
Closing the issue here; use referenced issue above to track.
