### ISSUE TITLE
Wiki: Modify install-instructions for Ubuntu 18.04

### ISSUE THREAD

**Issue by sundhaug92** [Microsoft/linux-vm-tools#42]
1. Split onboarding-instructions per distro
2. For ubuntu, use wget instead of curl, since wget is installed by default
3. Use $(lsb-release -rs) instead of 18.04, to support both 18.04 and 16.04 in the same instruction
4. Powershell has to run as administrator

**Comment by cwilhit** [comment]
@sundhaug92, we welcome you to open a PR with these changes to the wiki.

**Comment by sundhaug92** [comment]
Ok, been working on something for that, will try to get a PR for it

**Comment by sundhaug92** [comment]
I _do_ think however this bug should be up however until the PR is merged

**Comment by cwilhit** [comment]
Updated the wiki with the latest [revision ](https://github.com/Microsoft/linux-vm-tools/wiki/Onboarding:-Ubuntu/7f1b741df10bd4a642e1c2b9799528e6aa695964) with this feedback.
