### ISSUE TITLE
Window resizing

### ISSUE THREAD

**Issue by nxsh** [Microsoft/linux-vm-tools#43]
Forgive me if this is very basic but I have been using Hyper-V to virtualise Linux and the main issue I had was that I could not resize the window without editing config files and rebooting. 

I came across this Enhanced Session mode for Linux as I saw the [blog post](https://blogs.technet.microsoft.com/virtualization/2018/02/28/sneak-peek-taking-a-spin-with-enhanced-linux-vms/) stating that window resizing has been added. The additions have been very convenient coming from the basic session (especially the drive passthrough). 

However I still cannot resize the window as I can with other applications, I can only select a resolution upon starting. Have I installed incorrectly or is this feature not available yet?

**Comment by worthwhileindustries** [comment]
I also saw this as a touted feature but, was unable to get it to work via RDP or Connect through hyper-v

**Comment by cwilhit** [comment]
@nxsh correct, as of today you may only resize the window on initial connection beyond the previously static ~1024x768 window. 

The RDP protocol does support dynamic window resizing while the connection is running, but xrdp (the implementation of RDP we are using the Linux VM) is missing this module. This could be a feature request for future releases.

**Comment by worthwhileindustries** [comment]
@cwilhit how do we make this an official feature request?

**Comment by sundhaug92** [comment]
@worthwhileindustries I think that's an upstream issue, in which case it's neutrinolabs/xrdp

**Comment by cwilhit** [comment]
Since this is a feature request in xrdp, you can track via neutrinolabs/xrdp#448

**Comment by nxsh** [comment]
@cwilhit Thanks for clarifying that for me, hopefully it'll get added to xrdp at some point
