### ISSUE TITLE
Typo in install.sh?

### ISSUE THREAD

**Issue by oldium** [Microsoft/linux-vm-tools#44]
Just spotted the following typo:

https://github.com/Microsoft/linux-vm-tools/blob/8b41356c10cb0c85dce188716fd0e99a7293ad70/ubuntu/16.04/install.sh#L95

According to example in http://c-nergy.be/blog/?p=12043 shouldn't it be `subject.isInGroup("{users}"))`?

**Comment by cwilhit** [comment]
Thanks for catching! Fixed.
