### ISSUE TITLE
Ubuntu 18.04 in Hyper-V Quick Create VM gallery

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/linux-vm-tools#48]
I'm opening this, because setting up Ubuntu 18.04 with acceptable graphics performance seems to be not there #28.

Microsoft has told to work on delivering Ubuntu support right from the [quick create VM gallery](https://blogs.technet.microsoft.com/virtualization/2018/02/28/sneak-peek-taking-a-spin-with-enhanced-linux-vms/).

Idea of this issue is that everyone who would like to use Ubuntu through Hyper-V, can track this issue, and once it's delivered to quick create gallery we know it's done.

**Comment by dbsavage** [comment]
excited to see this. not that i couldn't implement enhanced mode using the instructions you can find around the web.  but it'd be nice to just one-click install from the quick create vm gallery.  thx all.

**Comment by cwilhit** [comment]
Hey all, just a friendly ping to let you know that we're still working through the process of bringing this to the quick create gallery. Really appreciate your patience in the meantime. And sure, we can use this issue and I'll close it out once it goes live...

**Comment by didiermartiny** [comment]
Also eagerly waiting for the feature.

**Comment by raimaj** [comment]
Can't wait for this!

**Comment by tkiraga** [comment]
@cwilhit any chance to see other distros in the gallery. Personally would love to see Fedora there

**Comment by sundhaug92** [comment]
@tkiraga A tempfix would be to add a local gallery using the reg-key

**Comment by cwilhit** [comment]
You can now find the Ubuntu VM in the Quick Create Gallery. Thanks all for your patience up to this point--took a little longer than expected, but we got there: https://blogs.windows.com/buildingapps/2018/09/17/run-ubuntu-virtual-machines-made-even-easier-with-hyper-v-quick-create/#K45BZAclDJ9Ql6h6.97
