### ISSUE TITLE
Setting alternate primary mouse button does not affect enhanced session mode

### ISSUE THREAD

**Issue by patrickceg** [Microsoft/linux-vm-tools#51]
Environment / Prerequisites:
* Ubuntu 18.04.1 (the only thing that I don't have as default is that I turned the gnome 3 animations off)
* Enhanced session mode is turned on
* Windows 10 1803, up to date as of the time of the post (all updates installed, not using any insider editions)
* (EDIT 1): Mouse does not have special drivers - (the connected mice are a Mionix Avior 7000 and PERIMICE-508 but as shown in the screenshot both are a generic mouse for Windows)

Steps to reproduce:
1. In the Windows 10 host, go Settings->Devices-Mouse
2. Under "Select your primary button, select 'Right'"
3. Verify the right mouse button is indeed the primary button (and that the left mouse button is the secondary button)
4. Start the Ubuntu 18.04.1 guest
5. Log in to the guest in enhanced session mode
6. Open the Gnome Settings -> Devices -> Mouse and Touchpad
7. Under General -> Primary button, set primary button to right

![Screenshot of guest and host](https://github.com/patrickceg/issues-assets/blob/master/Microsoft-linux-vm-tools-mousesettings.png?raw=true)

Expected result: The right mouse button is now the primary button in the guest
Actual result: The LEFT (default) mouse button continues to be the primary button.

Notes:
I also did the following to see if any of these would work, in this order, with no effect:
1. Restart the guest
2. Restart the host
3. Restart the guest again after the host has been restarted
4. Attempt toggling the primary button inside the guest (it doesn't seem to have an effect)

**Comment by cwilhit** [comment]
@patrickceg I think you should track this request through the xorgxrdp issue I linked above, so I am going to close this issue.
