### ISSUE TITLE
Enhanced session loses alternative keyboard layouts between sessions

### ISSUE THREAD

**Issue by brandonforster** [microsoft/linux-vm-tools#53]
This bug probably has more to do with the weird keyboard layout I use and it's certainly not a frequent use case, but I notice it every day and wanted to report this edge case.

Reproduction steps:

1. Install Dverty keyboard layout on Windows at github.com/chid/dverty

2. Start enhanced session (I'm using Ubuntu 18.04) with Windows using Dverty layout.

3. Log in, respecting that xrdp login will use QWERTY layout.

4. Change Ubuntu's keyboard layout to Dvorak. It should correctly be Dvorak.

5. Close Hyper-V window, but DO NOT shut down VM.

6. Reopen session, login with xrdp. Layout will nominally be Dvorak but keymap will be QWERTY.

**Comment by cwilhit** [comment]
I believe this to be related to xrdp itself. After setting the keyboard layout to dvorak in your Ubuntu VM, did you try running [xrdp-genkeymap](https://www.mankier.com/8/xrdp-genkeymap)?

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
