### ISSUE TITLE
Lost "Open in Terminal" for SMB shares (actually lost access to shares)

### ISSUE THREAD

**Issue by CarlosRafi** [microsoft/linux-vm-tools#54]
I initially posted this problem at the MS TechNet announcement for the Linux VM enhancements for Hyper-V and was recommended by Craig White to post here too, so here it is.  I also found a solution to the problem but I'm posting this here because there are some rough edges around this.

--- Original post ---
I added the enhancements to my Ubuntu 16.04 VM on Win10 build 17134.165, both patched all the way to most recent. The performance of the GUI in Ubuntu improved a lot, can cut and paste from host to guest both ways, etc.

My problem is that now I cannot access a USB3 ext drive from an Ubuntu terminal, something I was able to easily do before. For instance, before enhancements (basic session mode) I would connect to a share in the host for the ext USB3 drive using Nautilus. Then, still in Nautilus, Right-click the folder I need from the USB3 drive, and use the option “Open in Terminal”. At this point a Terminal window opens with the directory set to the folder I chose in Nautilus. The path notation is like this: “/run/user/1000/gvfs/smb-share:server=machinename,share=f/downloads$”. This works exactly like this if I choose to use a Basic Session, but if I use Enhanced, the option to “Open in Terminal” disappears from Nautilus and I cannot even do it if I try to manually enter the path in Terminal.

To be clear, in Enhanced Session I can map to the USB3 drive in the host with Nautilus and use the files there with no problem, Nautilus uses the notation: smb://machinename/f/Downloads/. The problem is only from Terminal.
--- Original post ---

The solution I found is to restart gvfs with:
killall gvfsd
nautilus -q
nautilus

After this, when I look in /run/user/1000/gvfs I can see:
smb-share:server=machinename,share=d
smb-share:server=machinename,share=f
which were not there before.

And "Open in Terminal" is available in Nautilus.  All other Enhanced features seem to work fine too.  But, every once in a while I get a pop-up saying that there was an error and gives me the option to report it.  I still have not determined what the error is.

Carlos

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
