### ISSUE TITLE
Resizing and snapshotting

### ISSUE THREAD

**Issue by LossMentality** [microsoft/linux-vm-tools#55]
I appreciate the work done so far to provide an enhanced mode. I have some questions/comments. I'm using Ubuntu 18.04.

1a. Resize by dragging VM window border - is this possible? Right now, I have to reboot and use the resolution dialog that appears at start-up. Even if a drag-to-resize isn't available, am I missing some other way to do this without a reboot?

1b. Needing to use the resize dialog has another downside: I can't check "remember my settings" because I need to be able to access the dialog every time I boot in case I want to resize. This means I have to make all settings (e.g. shared drives) every time I boot.

1c. Similar to above, but users should be able to hit the maximize button on a VM window and have it fill the whole desktop.

2. With the resolution dialg, only certain aspect ratios seem to be supported. I have an ultrawide monitor, and the resolutions available from the dialog mean I run out of vertical space before I can use even half of the monitor's width - i.e. the ultrawide becomes more of a hindrance than a help.

3. VM Snapshots; every time I take one, I get booted out of enhanced mode and have to enter the remote desktop login again.

**Comment by cwilhit** [comment]
Hey @LossMentality, for your resizing questions: no there is no support for dynamic resize, as you suspected. This is a feature request in XRDP. You can track it via neutrinolabs/xrdp/448

Thanks for the feedback regarding snapshotting.

**Comment by petesherick** [comment]
Are custom resolutions possible?  I'm on a 1920x1080 and would like something along 1800x1000.

**Comment by DonneyF** [comment]
@petesherick You can define your own custom resolution when connecting for a resolution that's not provided by the default promp.

Simply navigate to `%APPDATA%\Roaming\Microsoft\Windows\Hyper-V\Client\1.0` and edit the `.config` file that pertains to the VM that you have (not `user.config`).

In the file there is a field for `DesktopSize` and that's where you define your own resolution. For example:

```
        <setting name="DesktopSize" type="System.Drawing.Size">
            <value>2160, 1260</value>
        </setting>
```

Save the file and the next time you enter the Enhanced Session it should automatically adjust to the resolution you defined.

**Comment by wongrm** [comment]
Hi @DonneyF.  Is there any other place this setting needs to be configured?  I changed my values in the DesktopSize setting but it doesn't seem to get picked up.  I can tell I'm using the correct file because when I run `vmconnect <host> <vnname> /edit` and set the resolution that way the DesktopSize value in the file I edited reverts.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
