### ISSUE TITLE
Using Alt Gr key causes an extra caret movement to the left.

### ISSUE THREAD

**Issue by webtroter** [microsoft/linux-vm-tools#58]
I use the French (Canada) keyboard layout in Windows and Ubuntu 18.04.

Using the Enhanced session, when I type a caracter using the AltGr modifier, the right caracter get typed, but the cursor goes back one position.

Ex : Typing avezina@example.org makes me type avezinaexample.org@ since typing @ uses AltGr+2, and that brings the caret to the position before the @.

EDIT : Well, now, it doesn't do exactly this anymore, but it still doesn't work correctly. Now it goes : Press AltGr, caret goes back one, press 2 to get @, @ gets on screen, before the caret, as it should.

![When Typing inside VSCode, or anywhere else](https://user-images.githubusercontent.com/8386808/45506354-f29c3d80-b75c-11e8-8e1f-f0b6e97107f3.gif)

![xev tests](https://user-images.githubusercontent.com/8386808/45506476-47d84f00-b75d-11e8-8a0e-0a05a36b30bb.gif)

[xev.log](https://github.com/Microsoft/linux-vm-tools/files/2380467/xev.log)

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
