### ISSUE TITLE
Drive redirection is semi-broken

### ISSUE THREAD

**Issue by cwilhit** [Microsoft/linux-vm-tools#6]
Repro:

**Drive redirection fails to show up completely.**
1. Run through the steps to set up an enhanced session mode VM.
2. Connect via enhanced mode and toggle on "Drives" under Local Resources.
3. The folder "thinclient_drives" is created but is not populated.

There is a way to get further...
**Drive redirection semi-breaks (fixed in 18.04)**
1. Run through the steps to setup an enhanced session mode VM.
2. Connect via enhanced mode and toggle on "Drives" under Local Resources.
3. Toggle off "Printers" under Local Devices and Resources.
4. The folder "thinclient_drives" is created, along with the drives the user selected to share.
5. Inside the shared drive, you can create directories/files that are reflected on the host, but these actions do not manifest in the VM's view of the shared drive.

**Comment by dankseman** [comment]
I get the same issue - you click on drives and they are blank.

**Comment by cwilhit** [comment]
Tested with latest 18.04 daily image from Canonical with current 18.04 script. Drive redirection works, **as long as you disable sharing printer**s with the guest VM

**Comment by dankseman** [comment]
Do the commands in web page work for 1804 (changing path)?

**Comment by dankseman** [comment]
I worked it out - the steps are same except you do not need config-user steps (and path name changes).
I can now see my host files and copy either way.

NEXT STEP - SOUND!

**Comment by oldium** [comment]
> Tested with latest 18.04 daily image from Canonical with current 18.04 script. Drive redirection works, as long as you disable sharing printers with the guest VM

Perfect, now the drives work - I had to disable printer sharing in order to see the shared drives, too.

**Comment by cwilhit** [comment]
Drive sharing confirmed to work, closing issue.
