### ISSUE TITLE
Create generic installation instructions

### ISSUE THREAD

**Issue by sundhaug92** [microsoft/linux-vm-tools#60]
To be used when a distro is not officially supported, things like:

* Use Windows 10 1803+ or equivalent Windows Server 2016
* Use Linux kernel >= x.xx
* Have autologin on the guest disabled
* Set the hv_sock module to autoload on boot
* Set these parameters in xrdp.ini
...

Would also help create support for new distros like CentOS (#57)

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
