### ISSUE TITLE
Ubuntu 16.04 VM on Windows 10 Hyper-V (Ubuntu Functions not working)

### ISSUE THREAD

**Issue by MedAnd** [microsoft/linux-vm-tools#68]
Functions are not working (nothing happens upon selection):

- About This Computer 
- System Settings...
- Selecting logged in user (Administrator)
- Shutdown Restart

![image](https://user-images.githubusercontent.com/13365135/46905346-275b0a80-cf3e-11e8-8a96-e1ffac065afe.png)

Misc:

Ubuntu VM fully patched 

cc @jterry75 @cwilhit

**Comment by albadokhon** [comment]
Yes. I'm facing the same issues on Ubuntu Mate (18.04.2). 

One thing to note though, on the GUI side it seems that you are not a sudoer even though your user is root. So if you try to execute any of these commands from terminal (like say: `sudo shutdown now`) It will go through...

Not sure if this is an issue or if this is how Xorg (Enhanced mode) supposed to work. 
And now actually I can't even go back to the Basic Mode.  Once I switch there the Mouse and Keyboard are NOT captured by the console...

I think it is all related. Lets wait for a feedback.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
