### ISSUE TITLE
Kubuntu and other desktop environments

### ISSUE THREAD

**Issue by Ephesos** [microsoft/linux-vm-tools#69]
Will there be support for other desktop environments other than Ubuntu in the quick gallery? I understand using the most popular option(Ubuntu), but currently it seems to be the slowest option as well.

**Comment by Ephesos** [comment]
Hi Craig, the slow remark comes after testing Gnome(Ubuntu, Debian) and KDE(Kubuntu, Suse) linux clients. 

Gnome feels considerably slower than KDE, even with window animations disabled. This was most noticeable with keystrokes registering late in VS Code or even in the terminal and windows redraws/refreshes.

I'll play a bit more with fresh installs and report the details in the user experience and performance issue, my main question was answered.

**Comment by clintonm9** [comment]
I am really trying to get this working on Kali Linux (which is basically Debian 9) with no luck. I can get RDP working through normal TCP, then I can switch to use the vsock and I do not get the enhanced mode. Not sure how to debug Hyper-V to see if it is even trying to use the enhanced mode. It is currently greyed out

**Comment by pablospe** [comment]
I managed to get KDE working using Ubuntu quick gallery (which works out of the box). 

I followed a variant of this:
    https://www.hiroom2.com/2018/05/07/ubuntu-1804-xrdp-kde-en


`sudo apt install kubuntu-desktop`
(select 'sddm' manager)

```
echo "startkde" > ~/.xsession
D=/usr/share/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop
C=/etc/xdg/xdg-plasma:/etc/xdg
C=${C}:/usr/share/kubuntu-default-settings/kf5-settings
cat <<EOF > ~/.xsessionrc
export XDG_SESSION_DESKTOP=KDE
export XDG_DATA_DIRS=${D}
export XDG_CONFIG_DIRS=${C}
EOF
```

**Comment by pablospe** [comment]
For avoiding Authentication Required dialog, create the following pkla file which will success authentication. You can use unix-user:* as Identity and no as ResultAny which will fail authentication.

```
cat <<EOF | \
  sudo tee /etc/polkit-1/localauthority/50-local.d/xrdp-NetworkManager.pkla
[Netowrkmanager]
Identity=unix-group:sudo
Action=org.freedesktop.NetworkManager.network-control
ResultAny=yes
ResultInactive=yes
ResultActive=yes
EOF

cat <<EOF | \
  sudo tee /etc/polkit-1/localauthority/50-local.d/xrdp-packagekit.pkla
[Netowrkmanager]
Identity=unix-group:sudo
Action=org.freedesktop.packagekit.system-sources-refresh
ResultAny=yes
ResultInactive=auth_admin
ResultActive=yes
EOF

sudo systemctl restart polkit
```

This is again from: https://www.hiroom2.com/2018/05/07/ubuntu-1804-xrdp-kde-en

**Comment by jjesse** [comment]
I know this issue is old but I had no problem on the latest build of Kubuntu (20.04 beta+) of following the manual instructions and everything worked.
While I would love to see additional versions in the Quick Create gallery the manual instructions worked great and didn't need any changes (of course).

Maybe some mention of the manual instructiosn working on any flavor of Ubuntu?

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
