### ISSUE TITLE
Debian support

### ISSUE THREAD

**Issue by joeangry** [Microsoft/linux-vm-tools#73]
Any plans for adding support for Debian based distributions? I've tried doing the steps in the install script myself but found no success. I tried on both Debian 9 and Kali Linux which is based on Debian.

**Comment by anthonws** [comment]
I'm using this in Kali Linux (Debian Based) and it works.

**Comment by S-dn-Y** [comment]
> 
> 
> I'm using this in Kali Linux (Debian Based) and it works.

+1 for wanting to know...
Can you elaborate?

**Comment by joeangry** [comment]
Turns out it works in Kali 2018.4  (64-bit) with the Ubuntu 18.04 scripts. After rebooting and running the PowerShell command on the VM I get the Enhanced Session Mode dialog. I had to log out of the account I was signed into before I could properly login using the enhanced session.

Thanks for your help @S-dn-Y
