### ISSUE TITLE
Pasting large files into the RDP session breaks storage on Ubuntu 18.04

### ISSUE THREAD

**Issue by dovry** [microsoft/linux-vm-tools#75]
I have an Ubuntu 18.04 Desktop manually installed (not the Hyper-V quick deploy version) with a 30GB provisioned disk (not dynamic) with a single partition using all of it.

Here's `fdisk -l` output
```
Disk /dev/sda: 30 GiB, 32212254720 bytes, 62914560 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0xc1bc07b4

Device     Boot Start      End  Sectors Size Id Type
/dev/sda1  *     2048 62912511 62910464  30G 83 Linux
```
Here is `df -Th` output
```
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/sda1      ext4       30G  8,8G   20G  32% /
```
Both of these commands suggest that there is a bunch of unused space (and there is, I'll get to that later) but when I paste a large file (~3 GB .iso in this case) I get this error:
![image](https://user-images.githubusercontent.com/15201298/50281655-7fd3ea00-0450-11e9-8dea-7094d92c44f6.png)
^notice the file size and transfer speed

Here's the examine info
![image](https://user-images.githubusercontent.com/15201298/50281792-e78a3500-0450-11e9-8f2e-db8cfc32ac79.png)

Here is the same file in Windows Explorer (~3 GB)
![image](https://user-images.githubusercontent.com/15201298/50281746-bd387780-0450-11e9-9a95-3b541e52170f.png)

BUT! when I copy the file from the shared-drives path to that same .iso that currently lives on the host machine, it copies over just fine and reports the same info Windows does. 
![image](https://user-images.githubusercontent.com/15201298/50281892-3e900a00-0451-11e9-80d4-c6d9cc6e9ed4.png)

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
