### ISSUE TITLE
How to optimize Ubuntu 16.04 to reach the same level of performance as the 18.04 Quick Create VM?

### ISSUE THREAD

**Issue by BishtSarthak** [microsoft/linux-vm-tools#79]
Test Device - Surface Book 2 15" i7/16 GB/512 GB & Surface Pro 5 i7/16 GB/ 512 GB
VM - 4 Core/ Gen 2/ dynamic RAM & 2 Core/ Gen 2/ dynamic RAM

I have configured XRDP for Ubuntu 16.04 as per the steps in the onboarding session. The cursor movements are smooth however there's significant lag between keyboard key press and text display on screen. 

Comparing with the quick create VM in Hyper-V (Ubuntu 18.04) on the same devices -
- Virtually zero lag in text input in 18.04
- 18.04 VM boots faster
- Application loading time (e.g. terminal/ firefox) is lower in 18.04

How can I further optimize my 16.04 VM to reach the same level of performance as the 18.04 Quick Create VM?

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
