### ISSUE TITLE
Does this work in Windows 2019 hyper-v?

### ISSUE THREAD

**Issue by sherif-elmetainy** [Microsoft/linux-vm-tools#80]
Hello
I am running Hyper-V on Windows Server 2019, Version 1809 (OS Build 17763.316) with all windows updates installed.

I tried the steps outlined [repo-wiki](https://github.com/Microsoft/linux-vm-tools/wiki/Onboarding:-Ubuntu#manual-config---ubuntu-1804) under the section "**Manual Config - Ubuntu 18.04**", and I didn't get the Enhanced Session to work.

I tried with Ubuntu desktop with both versions 18.04 and 18.04.2, neither of them worked. Both were installed as a minimal install, and automatic login disabled. 

I checked the xrdp logs in /var/log/xrdp.log I found the following error:

> [ERROR] Cannot read private key file /etc/xrdp/key.pem: Permission denied

I fixed the error by adding the xrdp user to the ssl-cert group (running command `sudo usermod -a -G ssl-cert xrdp`). I rebooted the virtual machine after running that command, the error didn't show up again in the logs, but still the Enhanced Session doesn't work.

**Comment by cwilhit** [comment]
Do you have autologin disabled for your VM?

**Comment by sherif-elmetainy** [comment]
@cwilhit yes I do.

**Comment by sherif-elmetainy** [comment]
I wondering if my issue is related to #76. 
May be some package update broke the script? I tried a new installation of Ubuntu 18.04 while commenting the line `apt update && apt upgrade -y` in the install.sh script, and not running the software update app in the desktop. However install.sh still installs several new packages with dependencies. 

So I am wondering an update to one of the packages or the dependencies broke the xrdp connection.

**Comment by sherif-elmetainy** [comment]
I guess it's me being stupid. Turns out Hyper-V enhanced session policy was off. I didn't know this setting existed, and didn't know that it's off by default in Windows Server.

Now I got enhanced session working, but I get a blank screen after login. I will close this one since the blank screen is unrelated.

**Comment by cwilhit** [comment]
Glad to hear you got it working (that policy is new for me as well--thanks for sharing).

When you say blank screen, do you mean a blank (say, black?) screen or do you see the Ubuntu desktop background but it's otherwise blank?

**Comment by sherif-elmetainy** [comment]
By blank I mean greenish blue screen (same background as the login screen). I found in the ~/.xorgxrdp.10.log the following error:

> Cannot open /dev/tty0 (Permission denied)

After some search, I found [this issue in xrdp repo](https://github.com/neutrinolabs/xrdp/issues/1159). The solutions suggested by users in that issue, worked for me.

I solved the issue by installing xserver-xorg-core, xorgxrdp and xserver-xorg-legacy packages.
Then changing file /etc/X11/Xwrapper.config and adding the line:
`needs_root_rights=yes`

After rebooting the guest OS, everything worked perfectly. So I guess the main issue is that either install.sh from this repo or xrdp package installation don't work directly and further steps are needed (at least not with the latest Ubuntu 18.04.2 ISO image that I used for installation).

I am inclined to believe that the issue is related to xrdp installation rather than install.sh, since I got the blank screen also with RDP client over a TCP connection. So I suppose the issue is not just limited to Enhanced Session.

Thanks a lot for your quick answers.

**Comment by gurpreetshanky** [comment]
Hi @sherif-elmetainy . Can you please tell me how did you solve this greenish blue screen problem?

**Comment by sherif-elmetainy** [comment]
@gurpreetshanky 
I installed the packages xserver-xorg-core, xorgxrdp and xserver-xorg-legacy
`sudo apt-get install xserver-xorg-core xorgxrdp  xserver-xorg-legacy`

Then I edited the file  /etc/X11/Xwrapper.config
`sudo nano  /etc/X11/Xwrapper.config`

After the file is open add the line
`needs_root_rights=yes`

Save the file, then reboot the guest OS.

**Comment by gurpreetshanky** [comment]
@sherif-elmetainy Thanks it works now. But I jumped to vmware now as it works better for me out of the box.

**Comment by DikSoft** [comment]
@sherif-elmetainy  , thank you!
