### ISSUE TITLE
Hyper-V Ubuntu 18.04 Quick Create disk size is too small

### ISSUE THREAD

**Issue by lostern** [microsoft/linux-vm-tools#82]
I like to work in a fullscreen Ubuntu VM.  The default disk size is just 12GB, when following the standard Hyper-V Quick Create instructions for creating an Ubuntu VM.  But if you create a VM from your own downloaded image, its Connect window won't resize automatically.  Here is a way to modify the Quick Create Ubuntu VM's disk size before the Ubuntu installation actually starts.
 
* Follow instructions for enabling Hyper-V in Windows 10, but stop before actually creating the VM:  https://www.tutorialspoint.com/windows10/windows10_virtualization.htm (See also https://github.com/Microsoft/linux-vm-tools/wiki/Onboarding:-Ubuntu
* Obtain a copy of the gparted-live-*-amd64.iso from here, https://gparted.org/download.php, or here, https://www.download3k.com/Install-GParted-LiveCD.html, and note its file directory location for later.  Be sure to check md5 and SHA1 checksums for validity.
* Click on Start, type Hyper-V, select Hyper-V Manager desktop app
* Under Actions, select Quick Create
* Select your desired Ubuntu desktop, for example Ubuntu 18.04.2 LTS
* Optional:  click on More Options, change Name; for example to <useralias>-desktop
* Click on Create Virtual Machine.  You will see a download page.  Wait until it is completed.  When it is done, you will see a splash page saying Virtual Machine created successfully.
* DON'T click connect just yet!  Instead, click on Edit Settings.
* Under Hardware ==> Add Hardware, click on SCSI Controller
* Select DVD Drive and click on Add.
* Under Media, select Image File, and browse to your gparted-live-*-amd64.iso, then click Apply at the bottom of the page.
* Select the other SCSI controller with the preinstalled drive image, and click on the Hard Drive (e.g. <useralias>-desktop.vhdx)
* Under Virtual Hard Disk, click the Edit button under the name of your desktop vhdx image.
* On the next screen, you will see the file location.  Click Next.
* On this screen, you will see three options:  Compact, Convert and Expand.  Click on Expand, then Next
* Enter the new size for your desktop image (e.g. 64GB) and click Next
* Review your settings, backing up to correct if necessary, then Finish
* On Settings page again, hit Apply 
* Under Hardware, click on Firmware
* Move gparted DVD drive to top of boot order and click Apply
* Click on OK to finish changing settings
* Back on Virtual Machine created successfully page, click Connect, then when the window comes up, Start
* When the GPARTED start screen comes up, cursor down to the boot to RAM option (probably the 3rd one down)
* Select default keyboard, US English, and "0" to boot X.
* Select /dev/sda1 and click on Resize/Move
* Adjust to new size, with no space preceding or following, then click Resize/Move
* Click Apply and Close
* Select File -> Exit
* If session is still running: back in Hyper-V Manager, select the VM and then Shut Down
* Go back into the VM Settings,
* Under Firmware, modify Boot settings -- move DVD drive with the GPARTED iso down to last, then click Apply
* Under the SCSI controller associated with the GPARTED iso DVD Drive, select DVD drive
* Under Media, select None, to avoid always having to mount GPARTED.
* Then click Apply and OK.
* Now Connect to the VM again.  It should start up with the regular Ubuntu installation using the enlarged disk size.

It would be nice if the Quick Create path allowed the user to resize the VM hard drive without having to use GPARTED

**Comment by mgaerber** [comment]
If the virtual machine greets you with `>>Start PXE over IPv4` you have to wait for about one minute...

**Comment by jterry75** [comment]
You can also:
```PowerShell
Resize-VHD -Path C:\Path\To\Install\Vhd.vhdx -SizeBytes 100GB
```

And then expand the ext4 partition in the guest.

**Comment by lostern** [comment]
Is it possible to do the Resize-VHD call before the Ubuntu installation starts?

**Comment by l33ds** [comment]
This issues is still relevant and time consuming. 12GB is not enough for an OS partition, and extending it after installation fails consistently for me. Quick Create should allow this simple option of setting the size of the OS partition without these workarounds.

**Comment by lostern** [comment]
I agree with your assessment.

In the interim, are you able to install a GPARTED iso as an additional SCSI device and boot from it?  If so, you should be able to extend the size of the disk.

Ted

**Comment by l33ds** [comment]
> I agree with your assessment. In the interim, are you able to install a GPARTED iso as an additional SCSI device and boot from it? If so, you should be able to extend the size of the disk. Ted From: l33ds <notifications@github.com> Sent: Wednesday, April 8, 2020 8:10 AM To: microsoft/linux-vm-tools <linux-vm-tools@noreply.github.com> Cc: Ted Stern <Louis.Stern@microsoft.com>; Author <author@noreply.github.com> Subject: Re: [microsoft/linux-vm-tools] Hyper-V Ubuntu 18.04 Quick Create disk size is too small (#82) Importance: High This issues is still relevant and time consuming. 12GB is not enough for an OS partition, and extending it after installation fails consistently for me. Quick Create should allow this simple option of setting the size of the OS partition without these workarounds. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Flinux-vm-tools%2Fissues%2F82%23issuecomment-611015119&data=02%7C01%7CLouis.Stern%40microsoft.com%7Cd6c454626154428df54b08d7dbceee29%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637219554115179349&sdata=ktGs8StymWry5ZHoScvpIZaDWHMb25Tfmxm3O6Fv6Nw%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALVSOVJJGYUTQBUO623CE73RLSHVDANCNFSM4HLV6OAA&data=02%7C01%7CLouis.Stern%40microsoft.com%7Cd6c454626154428df54b08d7dbceee29%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637219554115189337&sdata=qAarAHRlfFs%2BbI4v5ZoFct%2Fpu6dU1J9pOH%2BRLjm5UfA%3D&reserved=0>.

Yea it resolved the issue, but I think that's a great inconvenience. Also, most people are unaware of the issue/solution until the hit the point of no return when running out of space in the OS partition. For me, I had to delete the VM and reinstall my whole setup

**Comment by artiebob** [comment]
These steps work well
https://www.frodehus.dev/resize-disk-for-ubuntu-hyper-v-quick-create-image/

**Comment by mgaerber** [comment]
@artiebob gparted works but the issue was raised because the need to mount a live cd to expand the hard drive is quite a blocker.

**Comment by gitgani** [comment]
> I like to work in a fullscreen Ubuntu VM. The default disk size is just 12GB, when following the standard Hyper-V Quick Create instructions for creating an Ubuntu VM. But if you create a VM from your own downloaded image, its Connect window won't resize automatically. Here is a way to modify the Quick Create Ubuntu VM's disk size before the Ubuntu installation actually starts.
> 
> * Follow instructions for enabling Hyper-V in Windows 10, but stop before actually creating the VM:  https://www.tutorialspoint.com/windows10/windows10_virtualization.htm (See also https://github.com/Microsoft/linux-vm-tools/wiki/Onboarding:-Ubuntu
> * Obtain a copy of the gparted-live-*-amd64.iso from here, https://gparted.org/download.php, or here, https://www.download3k.com/Install-GParted-LiveCD.html, and note its file directory location for later.  Be sure to check md5 and SHA1 checksums for validity.
> * Click on Start, type Hyper-V, select Hyper-V Manager desktop app
> * Under Actions, select Quick Create
> * Select your desired Ubuntu desktop, for example Ubuntu 18.04.2 LTS
> * Optional:  click on More Options, change Name; for example to -desktop
> * Click on Create Virtual Machine.  You will see a download page.  Wait until it is completed.  When it is done, you will see a splash page saying Virtual Machine created successfully.
> * DON'T click connect just yet!  Instead, click on Edit Settings.
> * Under Hardware ==> Add Hardware, click on SCSI Controller
> * Select DVD Drive and click on Add.
> * Under Media, select Image File, and browse to your gparted-live-*-amd64.iso, then click Apply at the bottom of the page.
> * Select the other SCSI controller with the preinstalled drive image, and click on the Hard Drive (e.g. -desktop.vhdx)
> * Under Virtual Hard Disk, click the Edit button under the name of your desktop vhdx image.
> * On the next screen, you will see the file location.  Click Next.
> * On this screen, you will see three options:  Compact, Convert and Expand.  Click on Expand, then Next
> * Enter the new size for your desktop image (e.g. 64GB) and click Next
> * Review your settings, backing up to correct if necessary, then Finish
> * On Settings page again, hit Apply
> * Under Hardware, click on Firmware
> * Move gparted DVD drive to top of boot order and click Apply
> * Click on OK to finish changing settings
> * Back on Virtual Machine created successfully page, click Connect, then when the window comes up, Start
> * When the GPARTED start screen comes up, cursor down to the boot to RAM option (probably the 3rd one down)
> * Select default keyboard, US English, and "0" to boot X.
> * Select /dev/sda1 and click on Resize/Move
> * Adjust to new size, with no space preceding or following, then click Resize/Move
> * Click Apply and Close
> * Select File -> Exit
> * If session is still running: back in Hyper-V Manager, select the VM and then Shut Down
> * Go back into the VM Settings,
> * Under Firmware, modify Boot settings -- move DVD drive with the GPARTED iso down to last, then click Apply
> * Under the SCSI controller associated with the GPARTED iso DVD Drive, select DVD drive
> * Under Media, select None, to avoid always having to mount GPARTED.
> * Then click Apply and OK.
> * Now Connect to the VM again.  It should start up with the regular Ubuntu installation using the enlarged disk size.
> 
> It would be nice if the Quick Create path allowed the user to resize the VM hard drive without having to use GPARTED



Awesome,. it worked. But, after installation the screeen size is not full. Its partial. In earlier case (just quick create) would pop-up a window to adjust screen size. Thats one thing I'm missing.
++ One more change I observed. I couldnt resize the partition in the above way. I just tried multiple times and it would throw some errors without completing the partition. So I shrunk the disk 1st (from 12Gb to 9Gb) and after that was successful I tried resizing. That worked.

**Comment by ansgarbecker** [comment]
The [guide from Frode](https://www.frodehus.dev/resize-disk-for-ubuntu-hyper-v-quick-create-image/) helped me for my full 12gb disk with Ubuntu 20. Also, I found out these automatic checkpoints are causing errors when applying changes in GParted. So, I deleted that checkpoint in Hyper-V while the VM was offline. Then booted the VM with the GParted DVD and applied my wanted volume size without errors. This way I didn't need to set up applications and configuration in the VM again.

**Comment by lostern** [comment]
Frode’s guide essentially found the same thing I did – you can use GParted to resize your partition during VM creation, thus avoiding the problem of resizing when a checkpoint exists.

**Comment by josiasmueller** [comment]
This saved me after an eternity of failing with other approaches: http://linguist.is/2020/08/12/expand-ubuntu-disk-after-hyper-v-quick-create/

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
