### ISSUE TITLE
Consecutive sed invocations is problematic

### ISSUE THREAD

**Issue by liuw** [microsoft/linux-vm-tools#84]
https://github.com/microsoft/linux-vm-tools/blob/4dcc278f842ef1de4cc2c7b24ecb1c048415ff07/ubuntu/18.04/install.sh#L49-L55

The above snippet invokes sed several times which causes the _orig file to be overwritten.

The correct way to do this is to invoke sed only once with several commands, like this:

```
sed -i_orig -e 's/A/B/g' -e 's/C/D/g' file
```

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
