### ISSUE TITLE
Light-locker crash with Xfce/XUbuntu

### ISSUE THREAD

**Issue by tseward** [microsoft/linux-vm-tools#91]
I'm running XUbuntu [19.04] because I did not want to use Gnome.

While I can use an Enhanced Session, I see the same error as #31 when logging into the Xfce desktop. I'm unsure if there is any impact to this error beyond the login crash, but would like to resolve it none the less.

    light-locker crashed with signal 5 in g_type_create_instance()

I ran through the manual configuration steps via the script in the wiki for Ubuntu 18.04.

**Comment by tseward** [comment]
Removal of the `light-locker` package resolved it (obviously :)). Based on the package description, I don't think this is much of an issue to remove it as it serves as a secure way of locking a workstation.

**Comment by IntoCpp** [comment]
Official bug report: https://bugs.launchpad.net/ubuntu/+source/light-locker/+bug/1745259 

I also get this, running Ubuntu in a local VM, so I disabled the screen-lock.
