### ISSUE TITLE
Quick Create Gallery doesn't have Ubutnu listed

### ISSUE THREAD

**Issue by NeoMatrixJR** [microsoft/linux-vm-tools#92]
I only have MSIX Packaging Tool Environment and Windows 10 dev environment.  Win 10 v.1809

**Comment by xsebas21** [comment]
The content of the gallery is retrieved by default from https://go.microsoft.com/fwlink/?linkid=851584 which is a JSON file. This URL should be in the registry:

Path:
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\`

Item:
`GalleryLocations `

Go to the regedit and check that the value is pointing to:
https://go.microsoft.com/fwlink/?linkid=851584

**Comment by NeoMatrixJR** [comment]
Interesting...That item doesn't exist in my registry...
Also curious, I have a co-worker that DOES have the items in his quick create list, but also doesn't have this registry key.

**Comment by xsebas21** [comment]
Strange. You could try creating your own gallery source, as suggested here:

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/custom-gallery#build-a-new-gallery-source

**Comment by NeoMatrixJR** [comment]
nm... have conflict. VMWare PowerCLI overrides default `set-vm` - command works with `Hyper-V\Set-VM`
