### ISSUE TITLE
New version of xrdp on Arch Linux won't start

### ISSUE THREAD

**Issue by rafaeljpc** [microsoft/linux-vm-tools#94]
Hello,

Sorry to bother. But today (2019-09-02) manjaro received a AUR update at xrdp package to 0.9.11 and it doesn't start anymore. I tried to reinstall it, with no success.

```
> systemctl status xrdp
● xrdp.service - xrdp daemon
   Loaded: loaded (/usr/lib/systemd/system/xrdp.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2019-09-02 12:02:18 -03; 1h 33min ago
     Docs: man:xrdp(8)
           man:xrdp.ini(5)
  Process: 459 ExecStart=/usr/bin/xrdp (code=exited, status=1/FAILURE)

set 02 12:02:16 lst-dev-note22-vm-linux systemd[1]: Starting xrdp daemon...
set 02 12:02:17 lst-dev-note22-vm-linux xrdp[459]: (459)(140131473856704)[INFO ] address [0.0.0.0] port [3389] mode 3
set 02 12:02:17 lst-dev-note22-vm-linux xrdp[459]: (459)(140131473856704)[INFO ] listening to port 3389 on 0.0.0.0
set 02 12:02:17 lst-dev-note22-vm-linux xrdp[459]: (459)(140131473856704)[ERROR] trans_listen_address failed
set 02 12:02:18 lst-dev-note22-vm-linux xrdp[459]: (459)(140131473856704)[DEBUG] Closed socket 7 (AF_VSOCK cid -1 port -1)
set 02 12:02:18 lst-dev-note22-vm-linux xrdp[459]: (459)(140131473856704)[ERROR] Failed to start xrdp daemon, possibly address already in use.
set 02 12:02:18 lst-dev-note22-vm-linux systemd[1]: xrdp.service: Control process exited, code=exited, status=1/FAILURE
set 02 12:02:18 lst-dev-note22-vm-linux systemd[1]: xrdp.service: Failed with result 'exit-code'.
set 02 12:02:18 lst-dev-note22-vm-linux systemd[1]: Failed to start xrdp daemon.
```

https://aur.archlinux.org/packages/xrdp/

**Comment by rafaeljpc** [comment]
Found some infos at the other xrdp project

https://github.com/neutrinolabs/xrdp/issues/1403

**Comment by metalefty** [comment]
`use_vsock=yes` is not prefered since xrdp v0.9.11 or later.

**Comment by metalefty** [comment]
Try `port=vsock://<cid>:<port>` instead of `use_vsock=yes`. I'm thinking of `use_vsock`switch from xrdp in future.

**Comment by joegle** [comment]
> Try `port=vsock://<cid>:<port>` instead of `use_vsock=yes`. I'm thinking of `use_vsock`switch from xrdp in future.

What is the `cid` value here?

**Comment by prydom** [comment]
@joegle the correct value is -1. Unfortunately there's a bug in xrdp that prevents setting negative values for `cid`. See https://github.com/neutrinolabs/xrdp/issues/1403#issuecomment-533837144, where I proposed a workaround. I'll likely look into developing a more robust patch so both configuration styles will work once again.

```
/* The vSocket equivalent of INADDR_ANY.  This works for the svm_cid field of
 * sockaddr_vm and indicates the context ID of the current endpoint.
 */

#define VMADDR_CID_ANY -1U
```
source: https://github.com/torvalds/linux/blob/f7c3bf8fa7e5a8e45f4a8e82be6466157854b59b/include/uapi/linux/vm_sockets.h#L87

**Comment by joegle** [comment]
@prydom Thanks. 

I ended up changing the git tag in the AUR package to use v0.9.10

**Comment by PeterW007** [comment]
I have the same issue. Probably the most efficient solution is to roll back to 9.10.

**Comment by StefanoD** [comment]
Same problem here.

**Comment by multipitch** [comment]
The issue regarding xrdp not handling negative cid numbers has been resolved in the current release.
To fix an existing installation, install `xrdp 0.9.12` from AUR and make the following changes to `/etc/xrdp/xrdp.ini`:
```
port=vsock://-1:3389
use_vsock=false
```
I've submitted a [PR](https://github.com/microsoft/linux-vm-tools/pull/99) on this.
See also https://github.com/neutrinolabs/xrdp/issues/1403

**Comment by anlx-sw** [comment]
i did a fresh git pull and reinstalled linux-vm-tools on my manjaro vm. afterwards i set  "use_vsock=false"  (port=vsock://-1:3389 was already set). unfortunately the enhanced session mode is still not working.

[xrdp-error-log.txt](https://github.com/microsoft/linux-vm-tools/files/4061125/xrdp-error-log.txt)

does anyone have an idea what's still wrong?

**Comment by multipitch** [comment]
I'm finding that it works when I select Xvnc but not when I select Xorg - can you try that? I've commented out all the other sections of my xrdp.ini so that I can only selecte Xvnc on the login screen to simplify things for me.

**Comment by anlx-sw** [comment]
i just checked that xvnc is also not working for me.

**Comment by seliger** [comment]
I don't have an answer, but here is an additional clue. In Ubuntu 20.04, adding security="" to disable AppArmor allows xrdp to come up properly. This is with port=vsock://-1:3389 and vsock=false.

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
