### ISSUE TITLE
Blog Post Missing

### ISSUE THREAD

**Issue by insightful-tools** [microsoft/linux-vm-tools#96]
From the main readme:
"This repository is the home of a set of bash scripts that enable and configure an enhanced session mode on Linux VMs (Ubuntu, arch) for Hyper-V. You can learn more about this in our blog post."

The "blog post" link:
https://blogs.technet.microsoft.com/virtualization/2018/02/28/sneak-peek-taking-a-spin-with-enhanced-linux-vms/

Is now a dead end.

**Comment by xsebas21** [comment]
It is redirecting to the virtualization site from MS, but you can see an
updated blog post link in the very first row:

https://techcommunity.microsoft.com/t5/Virtualization/Sneak-Peek-Taking-a-Spin-with-Enhanced-Linux-VMs/ba-p/382415
